// Code generated by protoc-gen-go. DO NOT EDIT.
// source: execResult.proto

package db

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecResultMsg struct {
	LastInsertId         int64    `protobuf:"varint,1,opt,name=lastInsertId,proto3" json:"lastInsertId,omitempty"`
	RowsAffected         int64    `protobuf:"varint,2,opt,name=rowsAffected,proto3" json:"rowsAffected,omitempty"`
	ErrCode              int64    `protobuf:"varint,3,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,4,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResultMsg) Reset()         { *m = ExecResultMsg{} }
func (m *ExecResultMsg) String() string { return proto.CompactTextString(m) }
func (*ExecResultMsg) ProtoMessage()    {}
func (*ExecResultMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_55ca9a81281b5006, []int{0}
}

func (m *ExecResultMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResultMsg.Unmarshal(m, b)
}
func (m *ExecResultMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResultMsg.Marshal(b, m, deterministic)
}
func (m *ExecResultMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResultMsg.Merge(m, src)
}
func (m *ExecResultMsg) XXX_Size() int {
	return xxx_messageInfo_ExecResultMsg.Size(m)
}
func (m *ExecResultMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResultMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResultMsg proto.InternalMessageInfo

func (m *ExecResultMsg) GetLastInsertId() int64 {
	if m != nil {
		return m.LastInsertId
	}
	return 0
}

func (m *ExecResultMsg) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *ExecResultMsg) GetErrCode() int64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ExecResultMsg) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecResultMsg)(nil), "db.ExecResultMsg")
}

func init() { proto.RegisterFile("execResult.proto", fileDescriptor_55ca9a81281b5006) }

var fileDescriptor_55ca9a81281b5006 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xad, 0x48, 0x4d,
	0x0e, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4a, 0x49,
	0x52, 0xea, 0x64, 0xe4, 0xe2, 0x75, 0x85, 0x4b, 0xf8, 0x16, 0xa7, 0x0b, 0x29, 0x71, 0xf1, 0xe4,
	0x24, 0x16, 0x97, 0x78, 0xe6, 0x15, 0xa7, 0x16, 0x95, 0x78, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x30, 0x07, 0xa1, 0x88, 0x81, 0xd4, 0x14, 0xe5, 0x97, 0x17, 0x3b, 0xa6, 0xa5, 0xa5, 0x26, 0x97,
	0xa4, 0xa6, 0x48, 0x30, 0x41, 0xd4, 0x20, 0x8b, 0x09, 0x49, 0x70, 0xb1, 0xa7, 0x16, 0x15, 0x39,
	0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x83, 0xa5, 0x61, 0x5c, 0x21, 0x31, 0x2e, 0xb6, 0xd4, 0xa2, 0x22,
	0xdf, 0xe2, 0x74, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x2f, 0x89, 0x0d, 0xec, 0x2c,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x52, 0xf8, 0xd5, 0xaa, 0x00, 0x00, 0x00,
}
