// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queryResult.proto

//包名，通过protoc生成时go文件时

package db

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 查询返回结果
type QueryResultMsg struct {
	Columns              []string           `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Datalength           int64              `protobuf:"varint,2,opt,name=datalength,proto3" json:"datalength,omitempty"`
	ErrCode              int64              `protobuf:"varint,3,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string             `protobuf:"bytes,4,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Data                 []*QueryResultData `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryResultMsg) Reset()         { *m = QueryResultMsg{} }
func (m *QueryResultMsg) String() string { return proto.CompactTextString(m) }
func (*QueryResultMsg) ProtoMessage()    {}
func (*QueryResultMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_669a2ffc32a17c66, []int{0}
}

func (m *QueryResultMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResultMsg.Unmarshal(m, b)
}
func (m *QueryResultMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResultMsg.Marshal(b, m, deterministic)
}
func (m *QueryResultMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultMsg.Merge(m, src)
}
func (m *QueryResultMsg) XXX_Size() int {
	return xxx_messageInfo_QueryResultMsg.Size(m)
}
func (m *QueryResultMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultMsg.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultMsg proto.InternalMessageInfo

func (m *QueryResultMsg) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *QueryResultMsg) GetDatalength() int64 {
	if m != nil {
		return m.Datalength
	}
	return 0
}

func (m *QueryResultMsg) GetErrCode() int64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *QueryResultMsg) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *QueryResultMsg) GetData() []*QueryResultData {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryResultData struct {
	Data                 []*any.Any `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryResultData) Reset()         { *m = QueryResultData{} }
func (m *QueryResultData) String() string { return proto.CompactTextString(m) }
func (*QueryResultData) ProtoMessage()    {}
func (*QueryResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_669a2ffc32a17c66, []int{1}
}

func (m *QueryResultData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResultData.Unmarshal(m, b)
}
func (m *QueryResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResultData.Marshal(b, m, deterministic)
}
func (m *QueryResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultData.Merge(m, src)
}
func (m *QueryResultData) XXX_Size() int {
	return xxx_messageInfo_QueryResultData.Size(m)
}
func (m *QueryResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultData.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultData proto.InternalMessageInfo

func (m *QueryResultData) GetData() []*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryResultMsg)(nil), "db.QueryResultMsg")
	proto.RegisterType((*QueryResultData)(nil), "db.QueryResultData")
}

func init() { proto.RegisterFile("queryResult.proto", fileDescriptor_669a2ffc32a17c66) }

var fileDescriptor_669a2ffc32a17c66 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xbd, 0x4e, 0x04, 0x21,
	0x14, 0x85, 0xc3, 0xb2, 0xae, 0xd9, 0x6b, 0xa2, 0x11, 0x8d, 0x41, 0x0b, 0x43, 0xb6, 0x91, 0x8a,
	0x49, 0xb4, 0xb4, 0x32, 0xda, 0x4e, 0x21, 0x6f, 0x00, 0x82, 0x58, 0x20, 0x28, 0x3f, 0xc5, 0x3c,
	0x90, 0xef, 0x69, 0x86, 0x99, 0x89, 0x13, 0xcb, 0x73, 0xbe, 0xfb, 0x25, 0xf7, 0xc0, 0xf9, 0x77,
	0xb5, 0x69, 0x90, 0x36, 0x57, 0x5f, 0xc4, 0x57, 0x8a, 0x25, 0x92, 0x8d, 0xd1, 0x37, 0xd7, 0x2e,
	0x46, 0xe7, 0x6d, 0xd7, 0x1a, 0x5d, 0xdf, 0x3b, 0x15, 0x86, 0x09, 0x1f, 0x7e, 0x10, 0x9c, 0xbe,
	0xfe, 0x49, 0x7d, 0x76, 0x84, 0xc2, 0xf1, 0x5b, 0xf4, 0xf5, 0x33, 0x64, 0x8a, 0x18, 0xe6, 0x7b,
	0xb9, 0x44, 0x72, 0x0b, 0x60, 0x54, 0x51, 0xde, 0x06, 0x57, 0x3e, 0xe8, 0x86, 0x21, 0x8e, 0xe5,
	0xaa, 0x19, 0x4d, 0x9b, 0xd2, 0x73, 0x34, 0x96, 0xe2, 0x06, 0x97, 0x48, 0xae, 0x60, 0x67, 0x53,
	0xea, 0xb3, 0xa3, 0x5b, 0x86, 0xf8, 0x5e, 0xce, 0x89, 0xdc, 0xc1, 0x76, 0xf4, 0xe9, 0x11, 0xc3,
	0xfc, 0xe4, 0xfe, 0x42, 0x18, 0x2d, 0x56, 0xdf, 0xbc, 0xa8, 0xa2, 0x64, 0x3b, 0x38, 0x3c, 0xc2,
	0xd9, 0x3f, 0x40, 0xf8, 0xec, 0xa2, 0xe6, 0x5e, 0x8a, 0x69, 0xa4, 0x58, 0x46, 0x8a, 0xa7, 0x30,
	0x4c, 0xb2, 0xde, 0xb5, 0xee, 0xe1, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xca, 0x67, 0x4d, 0x1f,
	0x01, 0x00, 0x00,
}
